# azure-pipelines.yml

trigger:
- main

pool:
  name: 'Default' 
  demands: 
  - agent.name -equals EJAC 

variables:
  # CORREÇÃO 1: Caminho Exato do arquivo de solução (SLN)
  solution: 'apitempodio/APITempoDIO/APITempoDIO.sln' 
  buildConfiguration: 'Release'
  
steps:
- checkout: self
  displayName: 'Checkout do Repositório'

- task: UseDotNet@2
  displayName: 'Instalar .Net SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore $(solution)
  displayName: 'Restaurar Solution'

- script: dotnet build $(solution) --configuration $(buildConfiguration)
  displayName: 'Build Solution'

- script: dotnet test $(solution) --configuration $(buildConfiguration) --no-build --collect "XPlat Code Coverage"
  displayName: 'Executar Testes e Coletar Cobertura'

- task: Docker@2
  displayName: 'Build e Push para ACR'
  inputs:
    containerRegistry: 'acrapidemoemanoel'
    repository: 'api-dio-test'
    command: 'buildAndPush'
    Dockerfile: 'apitempodio/APITempoDIO/Dockerfile' 
    tags: |
      $(Build.BuildId)
      latest